"""empty message

Revision ID: b08476482559
Revises: 23069f21797f
Create Date: 2017-04-20 23:27:35.192989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08476482559'
down_revision = '23069f21797f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('promotions', sa.Column('name', sa.Unicode(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'name')
    op.drop_column('promotions', 'content')
    # ### end Alembic commands ###
