"""empty message

Revision ID: 23069f21797f
Revises: 
Create Date: 2017-04-18 19:11:11.140133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23069f21797f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dresses',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Unicode(length=100), nullable=False),
    sa.Column('activation_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('season', sa.Unicode(length=20), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('images', mysql.JSON(), nullable=True),
    sa.Column('brand', mysql.JSON(), nullable=True),
    sa.Column('ratings', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('promotions',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dress_promotions',
    sa.Column('dress_uid', sa.Unicode(length=100), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dress_uid'], ['dresses.uid'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dress_promotions')
    op.drop_table('promotions')
    op.drop_table('dresses')
    # ### end Alembic commands ###
